### PR TITLE
dix: remove client->lastDrawable/lastGC

### LINKED ISSUE #306: Segmentation fault in GetGeometry
With 3.5.99.3 on ScientificLinux 7.2:
```
Core was generated by `/usr/lib64/nx/bin/x2goagent -extension XFIXES -nolisten tcp -nolisten tcp -dpi'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f2cc57ffecc in GetGeometry (client=client@entry=0x7f2cc6a758c0,
    rep=rep@entry=0x7ffdd1f56d50) at ../../dix/dispatch.c:799
799         rep->root = pDraw->pScreen->root->drawable.id;
(gdb) print *pDraw
$1 = {type = 80 'P', class = 244 '\364', depth = 12 '\f', bitsPerPixel = 202 '\312',
  id = 139830223829944, x = -2992, y = -13812, width = 32556, height = 0,
  pScreen = 0x7f2cca0cf450, serialNumber = 2454677}
(gdb) print *pDraw->pScreen
$2 = {myNum = 0, id = 1089, width = 28224, height = -14175, mmWidth = 32556, mmHeight = 0,
  numDepths = 30448, rootDepth = 56 '8', allowedDepths = 0x7f2cc73876f0,
  rootVisual = 139830297655024, defColormap = 48, minInstalledCmaps = 1041,
  maxInstalledCmaps = 0, backingStoreSupport = 0 '\000', saveUnderSupport = 0 '\000',
  whitePixel = 139830410699712, blackPixel = 139830319368080, rgf = 0, GCperDepth = {0x0, 0x0,
    0x0, 0x0, 0x0, 0x0, 0x59, 0x7f2ccdf568e0, 0x0}, PixmapPerDepth = {0x4},
  devPrivate = 0x7f2cc692a360, numVisuals = 0, visuals = 0x0, root = 0x0, WindowPrivateLen = 0,
  WindowPrivateSizes = 0x0, totalWindowSize = 0, GCPrivateLen = 0, GCPrivateSizes = 0x0,
  totalGCSize = 0, CloseScreen = 0x0, QueryBestSize = 0x0, SaveScreen = 0x8,
  GetImage = 0x7f2cc8f36d80, GetSpans = 0x0, PointerNonInterestBox = 0x0, SourceValidate = 0x0,
  CreateWindow = 0x0, DestroyWindow = 0x0, PositionWindow = 0x0, ChangeWindowAttributes = 0x0,
  RealizeWindow = 0x0, UnrealizeWindow = 0x0, ValidateTree = 0x0, PostValidateTree = 0x0,
  WindowExposures = 0x0, PaintWindowBackground = 0x0, PaintWindowBorder = 0x0, CopyWindow = 0x0,
  ClearToBackground = 0x0, ClipNotify = 0x0, RestackWindow = 0x0, CreatePixmap = 0x0,
  DestroyPixmap = 0x0, SaveDoomedAreas = 0x0, RestoreAreas = 0x0, ExposeCopy = 0x0,
  TranslateBackingStore = 0x0, ClearBackingStore = 0x0, DrawGuarantee = 0x0, BackingStoreFuncs = {
    SaveAreas = 0x0, RestoreAreas = 0x0, SetClipmaskRgn = 0x0, GetImagePixmap = 0x0,
    GetSpansPixmap = 0x0}, RealizeFont = 0x13, UnrealizeFont = 0x7f2cc883d2c0,
  ConstrainCursor = 0x0, ConstrainCursorHarder = 0x14, CursorLimits = 0x7f2cc6aba090,
  DisplayCursor = 0x0, RealizeCursor = 0x0, UnrealizeCursor = 0x0, RecolorCursor = 0x0,
  SetCursorPosition = 0x0, CreateGC = 0x0, CreateColormap = 0x0, DestroyColormap = 0x0,
  InstallColormap = 0x0, UninstallColormap = 0x0, ListInstalledColormaps = 0x18,
  StoreColors = 0x7f2cc8854150, ResolveColor = 0x0, BitmapToRegion = 0x0,
  SendGraphicsExpose = 0x0, BlockHandler = 0x0, WakeupHandler = 0x0, blockData = 0x0,
  wakeupData = 0x0, devPrivates = 0x0, CreateScreenResources = 0x0, ModifyPixmapHeader = 0x0,
  GetWindowPixmap = 0x0, SetWindowPixmap = 0x0, GetScreenPixmap = 0x0, SetScreenPixmap = 0x0,
  pScratchPixmap = 0x0, PixmapPrivateLen = 0, PixmapPrivateSizes = 0x0, totalPixmapSize = 0,
  MarkWindow = 0x0, MarkOverlappedWindows = 0x0, ChangeSaveUnder = 0x0,
  PostChangeSaveUnder = 0x0, MoveWindow = 0x0, ResizeWindow = 0x0, GetLayerWindow = 0x0,
  HandleExposures = 0x4c, ReparentWindow = 0x7f2cc6f4b370, SetShape = 0x0,
  ChangeBorderWidth = 0x0, MarkUnrealizedWindow = 0x0, ReplaceScanoutPixmap = 0x0}
(gdb) print *pDraw->pScreen->root
Cannot access memory at address 0x0
(gdb) list
794         SECURITY_VERIFY_GEOMETRABLE (pDraw, stuff->id, client, SecurityReadAccess);
795         memset(rep, 0, sizeof(xGetGeometryReply));
796         rep->type = X_Reply;
797         rep->length = 0;
798         rep->sequenceNumber = client->sequence;
799         rep->root = pDraw->pScreen->root->drawable.id;
800         rep->depth = pDraw->depth;
801         rep->width = pDraw->width;
802         rep->height = pDraw->height;
803
(gdb) bt
#0  0x00007f2cc57ffecc in GetGeometry (client=client@entry=0x7f2cc6a758c0,
    rep=rep@entry=0x7ffdd1f56d50) at ../../dix/dispatch.c:799
#1  0x00007f2cc57fffb1 in ProcGetGeometry (client=0x7f2cc6a758c0) at ../../dix/dispatch.c:835
#2  0x00007f2cc5806d1c in Dispatch () at NXdispatch.c:491
#3  0x00007f2cc57e9dcb in main (argc=17, argv=0x7ffdd1f573a8, envp=<optimized out>) at main.c:433
```

### PR DESCRIPTION
**Pull request by uli42**
This fixes ArcticaProject/nx-libs#306 and #322

Using client->lastDrawable and client->lastGC proved to be
unreliable. Doing the lookup everytime instead + checking for success
works!

### CODE REVIEW

**Comment by sunweaver** [comment]
Hi Uli,

On Sun Feb 19 00:25:05 2017 GMT+0100, Ulrich Sibiller wrote:
> @uli42 requested your review on: ArcticaProject/nx-libs#338 dix: remove client->lastDrawable/lastGC. 

This is awesome news. Do backport an X.org commit? Or did you come up with that change yourself. If it is an X.org commit, it should be documented in the commit msg.

I will take a more detailled look tomorrow.

Mike

-- 
Sent from my Fairphone (running Sailfish OS)...

**Comment by uli42** [comment]
I came up with that myself. But after that I found that Xorg upstream
has removed that code, too (after switching from XC_SECURITY to XACE).
And this patch is also not a backport, I have done it myself.

But I am still not sure if this is the right thing to do.

**Comment by Kimmax** [comment]
I build [this](https://github.com/uli42/nx-libs/tree/fix_%23306_%23322) and removed all nx related libs from the system. I installed all of the build packages and reinstalled x2goserver (Got uninstalled 'cause of deps). I could recreate the crashes.
After copying _nx-X11/programs/Xserver/nxagent_ over _/usr/bin/nxagent_ I cant recreate the crashes in Libreoffice.
Don't take that fix as approved yet, since we saw some randomness in the crashes. If we get through two days without a crash we should be good tho.
Thanks for tackling that bug

**Comment by sunweaver** [comment]
/usr/bin/nxagent is a shell script wrapping around /usr/lib/<multiarch>/nx/bin/nxagent.

So copied an ELF executable over a shell script. Please check your test setup once more. Thanks.

Mike

On Mon Feb 20 16:35:51 2017 GMT+0100, Kim Nürnberger wrote:
> I build this and removed all nx related libs from the system. I installed all of the build packages and reinstalled x2goserver (Got uninstalled 'cause of deps). I could recreate the crashes.
> After copying nx-X11/programs/Xserver/nxagent over /usr/bin/nxagent I cant recreate the crashes in Libreoffice.
> Don't take that fix as approved yet, since we saw some randomness in the crashes. If we get through two days without a crash we should be good tho.
> Thanks for tackling that bug 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or mute the thread.￼
>

-- 
Sent from my Fairphone (running Sailfish OS)...

**Comment by uli42** [comment]
Ad nxagent is linked using rpath now this should also work.

Vom Smartphone gesendet.

----- Ursprüngliche Nachricht -----
Von: "Mike Gabriel" <notifications@github.com>
Gesendet: ‎20.‎02.‎2017 19:17
An: "ArcticaProject/nx-libs" <nx-libs@noreply.github.com>
Cc: "Ulrich Sibiller" <uli42@gmx.de>; "Mention" <mention@noreply.github.com>
Betreff: Re: [ArcticaProject/nx-libs] dix: remove client->lastDrawable/lastGC(#338)

/usr/bin/nxagent is a shell script wrapping around /usr/lib/<multiarch>/nx/bin/nxagent. 

So copied an ELF executable over a shell script. Please check your test setup once more. Thanks. 

Mike 

On Mon Feb 20 16:35:51 2017 GMT+0100, Kim Nürnberger wrote: 
> I build this and removed all nx related libs from the system. I installed all of the build packages and reinstalled x2goserver (Got uninstalled 'cause of deps). I could recreate the crashes. 
> After copying nx-X11/programs/Xserver/nxagent over /usr/bin/nxagent I cant recreate the crashes in Libreoffice. 
> Don't take that fix as approved yet, since we saw some randomness in the crashes. If we get through two days without a crash we should be good tho. 
> Thanks for tackling that bug 
> — 
> You are receiving this because your review was requested. 
> Reply to this email directly, view it on GitHub, or mute the thread.￼ 
> 

-- 
Sent from my Fairphone (running Sailfish OS)...

**Comment by sunweaver** [comment]
I'll reference the made changes against X.org commits tomorrow and rebase the update branch of this PR slightly. Tomorrow.

**Comment by Kimmax** [comment]
No segfaults since this patch, I would say I can confirm this.
Thanks guys <3

**Comment by Ionic** [comment]
Hmmm... the interesting part is that we had something like this in e6f2f6427122dc4bc802acebf26f8cec16cd2f62, but then @sunweaver reverted it in @8c7d7bed969e556aa038aa2d45c7c9697dda9de9 because of code duplication, I guess?

**Comment by Ionic** [comment]
Err, wait, no, the commit was just backported partially only.

**Comment by Ionic** [comment]
I'll give you pointers on how/where to merge upstream changes in.

File: nx-X11/programs/Xserver/dix/dispatch.c [hunk 1]
```diff
@@ -3647,17 +3634,11 @@ void InitClient(ClientPtr client, int i, void * ospriv)
     if (i)
     {
 	client->closeDownMode = DestroyAll;
```
Comment (Ionic) [inline nx-X11/programs/Xserver/dix/dispatch.c]: Remove. Everything. But keep the `closeDownMode` change. Like in the second hunk here: https://cgit.freedesktop.org/xorg/xserver/diff/dix/dispatch.c?id=9a183d7ba50e31afa133cc03aee7991517a283ea

Also remove `FlushClientCaches()`, because even before your changes it's completely unused. Don't forget the definition in `nx-X11/programs/Xserver/include/dix.h`.

File: nx-X11/programs/Xserver/dix/dixutils.c [hunk 2]
```diff
@@ -241,13 +224,10 @@ SecurityLookupDrawable(XID rid, ClientPtr client, Mask access_mode)
...
-    if (client->trustLevel != XSecurityClientTrusted)
-	return (DrawablePtr)SecurityLookupIDByClass(client, rid, RC_DRAWABLE,
-						    access_mode);
-    if (client->lastDrawableID == rid)
-	return ((void *) client->lastDrawable);
     pDraw = (DrawablePtr)SecurityLookupIDByClass(client, rid, RC_DRAWABLE,
 						 access_mode);
+    if (client->trustLevel != XSecurityClientTrusted)
+      return (void *)pDraw;
     if (pDraw && (pDraw->type != UNDRAWABLE_WINDOW))
```
Comment (Ionic) [inline nx-X11/programs/Xserver/dix/dixutils.c]: Fold into one condition. You also inserted a whitespace error, but folding can remove that.
```C
    if ((client->trustLevel != XSecurityClientTrusted) || (pDraw && (pDraw->type != UNDRAWABLE_WINDOW)))
       return (void *)pDraw;
```

**Comment by uli42** [comment]
I have debugged a little further and saw that NXwindow.c/DeleteWindow is the place where the Drawable is freed. The lastDrawable pointer in the client structure is not touched there so it is clear that the client is referencing invalid data. But I could not find any hints in Xorg upstream how this was supposed to work at all.

**Comment by Ionic** [comment]
I just noticed we were missing reset calls in `nx-X11/programs/Xserver/dix/resource.c` for all resource types, which could well explain why this caching never worked out well for us.

We were just keeping invalid pointers around all the time.

**Comment by uli42** [comment]
@Ionic that could indeed explain that. What exactly is the code you found missing?

**Comment by Ionic** [comment]
Stuff like this:

```C
       if(clients[cid] && (id == clients[cid]->lastDrawableID))
       {
            clients[cid]->lastDrawable = (DrawablePtr)WindowTable[0];
            clients[cid]->lastDrawableID = WindowTable[0]->drawable.id;
        }
```

All around the file for the functions freeing resources. That was just an example, but you'll get the idea.

I still think we should go through with this PR and remove the caching completely, because Security lookups bypass that anyway.

**Comment by Ionic** [comment]
Aaand the reason for this is e6f2f6427122dc4bc802acebf26f8cec16cd2f62. It removed those calls, without removing all the other caching parts.

File: nx-X11/programs/Xserver/include/dix.h [hunk 3]
```diff
@@ -90,47 +90,32 @@ SOFTWARE.
...
-						      RC_DRAWABLE, mode);\
-	if (!pDraw) \
-	{\
-	    client->errorValue = did; \
-	    return BadDrawable;\
-	}\
-	if (pDraw->type == UNDRAWABLE_WINDOW)\
-	    return BadMatch;\
-    }
+    pDraw = (DrawablePtr) SecurityLookupIDByClass(client, did, \
```
Comment (Ionic) [inline nx-X11/programs/Xserver/include/dix.h]: You're adding a lot of whitespace changes in this file. What upstream did in this occasion was to leave indentation as it was (including the braces), so that the diff is smaller. Can you rework that in such a way? The benefit is leaving lines that didn't change as they were, so git blame will be better to understand. I'll give you an example for `SECURITY_VERIFY_DRAWABLE`, it would be great if you could apply the same logic to the other macros here.

Old code:
```C
#define SECURITY_VERIFY_DRAWABLE(pDraw, did, client, mode)\
    if (client->lastDrawableID == did && !client->trustLevel)\
	pDraw = client->lastDrawable;\
    else \
    {\
	pDraw = (DrawablePtr) SecurityLookupIDByClass(client, did, \
						      RC_DRAWABLE, mode);\
	if (!pDraw) \
	{\
	    client->errorValue = did; \
	    return BadDrawable;\
	}\
	if (pDraw->type == UNDRAWABLE_WINDOW)\
	    return BadMatch;\
    }
```

New code:
```C
#define SECURITY_VERIFY_DRAWABLE(pDraw, did, client, mode)\
    {\
	pDraw = (DrawablePtr) SecurityLookupIDByClass(client, did, \
						      RC_DRAWABLE, mode);\
	if (!pDraw) \
	{\
	    client->errorValue = did; \
	    return BadDrawable;\
	}\
	if (pDraw->type == UNDRAWABLE_WINDOW)\
	    return BadMatch;\
    }
```

**Review by Ionic — CHANGES_REQUESTED** [review]
And one more thing to do: remove `RC_CACHED` from `nx-X11/programs/Xserver/include/resource.h` and `nx-X11/programs/Xserver/dbe/dbe.c`.

File: nx-X11/programs/Xserver/dix/dispatch.c (hunk 1 above)
Comment (uli42) [reply nx-X11/programs/Xserver/dix/dispatch.c]: I am not sure what you mean by "Everything"

**Comment by uli42** [comment]
I have updated the PR as requested. I am a bit unsure about the last commit to remove RC_CACHED since Xorg upstream hasn't removed it,either.

File: nx-X11/programs/Xserver/include/resource.h [hunk 4]
```diff
@@ -58,7 +58,6 @@ SOFTWARE.
 typedef unsigned long RESTYPE;
 
 #define RC_VANILLA	((RESTYPE)0)
-#define RC_CACHED	((RESTYPE)1<<31)
```
Comment (Ionic) [inline nx-X11/programs/Xserver/include/resource.h]: You're right. Upstream hasn't removed this line, but removed RC_CACHED from the other three below. So let's keep the RC_CACHED macro around for now.

File: nx-X11/programs/Xserver/dix/dixutils.c [hunk 5]
```diff
@@ -241,15 +224,10 @@ SecurityLookupDrawable(XID rid, ClientPtr client, Mask access_mode)
...
-	return (DrawablePtr)SecurityLookupIDByClass(client, rid, RC_DRAWABLE,
-						    access_mode);
-    if (client->lastDrawableID == rid)
-	return ((void *) client->lastDrawable);
     pDraw = (DrawablePtr)SecurityLookupIDByClass(client, rid, RC_DRAWABLE,
 						 access_mode);
-    if (pDraw && (pDraw->type != UNDRAWABLE_WINDOW))
-        return (void *)pDraw;
+    if ((client->trustLevel != XSecurityClientTrusted) || (pDraw && (pDraw->type != UNDRAWABLE_WINDOW)))
+	return (void *)pDraw;
```
Comment (Ionic) [inline nx-X11/programs/Xserver/dix/dixutils.c:230]: Okay, but added whitespace error in the return line... try to keep it as spaces, not tabs.

File: nx-X11/programs/Xserver/include/resource.h (hunk 4 above)
Comment (Ionic) [reply nx-X11/programs/Xserver/include/resource.h]: I've been thinking about the reason for this and I think I understand why they don't delete the constant. Mostly for legacy-reasons. See, if old X11 client libraries set this, they expect a certain behavior. Deleting this constant from the server code may lead to someone re-introducing it for a different feature and then this will break badly with older X11 clients. So they just keep it around, doing nothing.

File: nx-X11/programs/Xserver/dix/dispatch.c (hunk 1 above)
Comment (Ionic) [reply nx-X11/programs/Xserver/dix/dispatch.c]: Like I said, in the same way upstream did.

Replace the `if (i) { ... } else { ... }` section with one single `client->closeDownMode = i ? DestroyAll : RetainPermanent;` statement.

**Review by Ionic — CHANGES_REQUESTED** [review]
Okay, just a few more changes. When you're done, rebase and squash the commits into one and report back, please.

File: nx-X11/programs/Xserver/include/resource.h (hunk 4 above)
Comment (uli42) [reply nx-X11/programs/Xserver/include/resource.h]: I disagree. resource.h is an internal header within the server. No clients involved.

Comment (Ionic) [reply nx-X11/programs/Xserver/include/resource.h]: They might have just forgotten to remove it, then. But given it's still there even in the newest version of xorg-xserver, we should also retain it for a smaller diff.

File: nx-X11/programs/Xserver/dix/dixutils.c (hunk 5 above)
Comment (uli42) [reply nx-X11/programs/Xserver/dix/dixutils.c:230]: Three lines above we have a tab. So I prefer to stay consistent (within the function at least). A whitespace overhaul is due anyway. But we once agreed the this shall be postponed until we reach the stage where xorg upstream did this.

Comment (Ionic) [reply nx-X11/programs/Xserver/dix/dixutils.c:230]: Yeah, this old X.Org version is riddled with mixed indentation and styles. The upstream folks ran a script to fix up whitespace in a consistent manner some time ago, so we'll need to do this as well. My point is aiming for the smallest diff, though (which may be a moot one since `git diff` supports the `-w` flag...)

As you like, really.

**Comment by uli42** [comment]
Ok, ready for the next round

**Review by Ionic — APPROVED** [review]
